let DelayTime = 0
let MotorSpeed = 0
input.onButtonPressed(Button.AB, () => {
    basic.showNumber(iBIT.ReadADC(ibitReadADC.ADC0))
    basic.showNumber(iBIT.ReadADC(ibitReadADC.ADC1))
    basic.showNumber(iBIT.ReadADC(ibitReadADC.ADC2))
    basic.showNumber(iBIT.ReadADC(ibitReadADC.ADC3))
    basic.showNumber(iBIT.ReadADC(ibitReadADC.ADC4))
    basic.showNumber(iBIT.ReadADC(ibitReadADC.ADC5))
    basic.showNumber(iBIT.ReadADC(ibitReadADC.ADC6))
    basic.showNumber(iBIT.ReadADC(ibitReadADC.ADC7))
})
MotorSpeed = 50
DelayTime = 1000
iBIT.MotorCH(ibitMotorCH.M1, ibitMotor.Forward, MotorSpeed)
basic.pause(DelayTime)
iBIT.MotorCH(ibitMotorCH.M1, ibitMotor.Backward, MotorSpeed)
basic.pause(DelayTime)
iBIT.MotorCH(ibitMotorCH.M2, ibitMotor.Forward, MotorSpeed)
basic.pause(DelayTime)
iBIT.MotorCH(ibitMotorCH.M2, ibitMotor.Backward, MotorSpeed)
basic.pause(DelayTime)
iBIT.Motor(ibitMotor.Forward, MotorSpeed)
basic.pause(DelayTime)
iBIT.Motor(ibitMotor.Backward, MotorSpeed)
basic.pause(DelayTime)
iBIT.Spin(ibitSpin.Left, MotorSpeed)
basic.pause(DelayTime)
iBIT.Spin(ibitSpin.Right, MotorSpeed)
basic.pause(DelayTime)
iBIT.MotorStop()
iBIT.Servo(ibitServo.SV1, MotorSpeed)
iBIT.Servo(ibitServo.SV2, MotorSpeed)
basic.pause(1500)
iBIT.Servo(ibitServo.SV1, 180)
iBIT.Servo(ibitServo.SV2, 180)
basic.pause(1500)
iBIT.ServoStop(ibitServo.SV1)
iBIT.ServoStop(ibitServo.SV2)
