let DelayTime = 0
let MotorSpeed = 0
input.onButtonPressed(Button.AB, () => {
    basic.showNumber(iBIT.ReadADC(ibitreadADC.ADC0))
    basic.showNumber(iBIT.ReadADC(ibitreadADC.ADC1))
    basic.showNumber(iBIT.ReadADC(ibitreadADC.ADC2))
    basic.showNumber(iBIT.ReadADC(ibitreadADC.ADC3))
    basic.showNumber(iBIT.ReadADC(ibitreadADC.ADC4))
    basic.showNumber(iBIT.ReadADC(ibitreadADC.ADC5))
    basic.showNumber(iBIT.ReadADC(ibitreadADC.ADC6))
    basic.showNumber(iBIT.ReadADC(ibitreadADC.ADC7))
})
MotorSpeed = 50
DelayTime = 1000
iBIT.MotorCH(ibitmotorCH.M1, ibitmotor.Forward, MotorSpeed)
basic.pause(DelayTime)
iBIT.MotorCH(ibitmotorCH.M1, ibitmotor.Backward, MotorSpeed)
basic.pause(DelayTime)
iBIT.MotorCH(ibitmotorCH.M2, ibitmotor.Forward, MotorSpeed)
basic.pause(DelayTime)
iBIT.MotorCH(ibitmotorCH.M2, ibitmotor.Backward, MotorSpeed)
basic.pause(DelayTime)
iBIT.Motor(ibitmotor.Forward, MotorSpeed)
basic.pause(DelayTime)
iBIT.Motor(ibitmotor.Backward, MotorSpeed)
basic.pause(DelayTime)
iBIT.Spin(ibitspin.Left, MotorSpeed)
basic.pause(DelayTime)
iBIT.Spin(ibitspin.Right, MotorSpeed)
basic.pause(DelayTime)
iBIT.MotorStop()
iBIT.Servo(ibitservo.SV1, MotorSpeed)
iBIT.Servo(ibitservo.SV2, MotorSpeed)
basic.pause(1500)
iBIT.Servo(ibitservo.SV1, 180)
iBIT.Servo(ibitservo.SV2, 180)
basic.pause(1500)
iBIT.ServoStop(ibitservo.SV1)
iBIT.ServoStop(ibitservo.SV2)
